//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Destiny.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public string OrderID { get; set; }
        public string AliPayCode { get; set; }
        public string WeChatPayCode { get; set; }
        public string Subject { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ProductCode { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
    }
}
