//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Destiny.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SixtyFourDong
    {
        public int ID { get; set; }
        public string FirstNum { get; set; }
        public string FirstNumName { get; set; }
        public string SecondNum { get; set; }
        public string SecondNumName { get; set; }
        public string Comment { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
